// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "TurboStream API for real-time data streaming and feed management with AI-powered analysis",
        "title": "TurboStream API",
        "termsOfService": "https://turboline.ai/terms",
        "contact": {
            "name": "API Support",
            "url": "https://turboline.ai/docs/api",
            "email": "dev@turboline.ai"
        },
        "license": {
            "name": "MPL-2.0",
            "url": "https://github.com/turboline-ai/turbostream?tab=MPL-2.0-1-ov-file"
        },
        "version": "1.0"
    },
    "host": "localhost:7210",
    "basePath": "/",
    "paths": {
        "/health": {
            "get": {
                "description": "Check the health status of the API server and its dependencies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HealthResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Register a new user account with email, password, and name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/login": {
            "post": {
                "description": "Login with email and password. Returns JWT token for authentication. Supports 2FA with TOTP token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get current authenticated user profile with token usage information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/UserProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/marketplace/feeds": {
            "get": {
                "description": "List all public feeds with optional filtering by category, search query, or limit",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Marketplace"
                ],
                "summary": "Browse public feeds",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of feeds to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search query for feed name or description",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by category key",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/FeedsListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new custom feed with WebSocket or HTTP connection configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Marketplace"
                ],
                "summary": "Create custom feed",
                "parameters": [
                    {
                        "description": "Feed configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateFeedRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/FeedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/marketplace/feeds/{id}": {
            "get": {
                "description": "Get detailed information about a specific feed by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Marketplace"
                ],
                "summary": "Get feed by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feed ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/FeedResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update feed properties. Only feed owner can update.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Marketplace"
                ],
                "summary": "Update feed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feed ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Feed update data (partial update supported)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/UpdateFeedRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/FeedResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a feed. Only feed owner can delete.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Marketplace"
                ],
                "summary": "Delete feed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feed ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/marketplace/subscribe/{feedId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Subscribe to a feed to receive real-time updates via WebSocket",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Marketplace"
                ],
                "summary": "Subscribe to feed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feed ID",
                        "name": "feedId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SubscriptionResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/marketplace/unsubscribe/{feedId}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Unsubscribe from a feed",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Marketplace"
                ],
                "summary": "Unsubscribe from feed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Feed ID",
                        "name": "feedId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/marketplace/subscriptions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all active subscriptions for current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Marketplace"
                ],
                "summary": "List user subscriptions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/SubscriptionsListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/llm/providers": {
            "get": {
                "description": "Get list of available LLM providers (OpenAI, Anthropic, Google, Mistral, xAI, Ollama, Azure)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM"
                ],
                "summary": "Get LLM providers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ProvidersResponse"
                        }
                    }
                }
            }
        },
        "/api/llm/query": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Query feed data with an LLM. Returns complete response with token usage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LLM"
                ],
                "summary": "Query feed with LLM",
                "parameters": [
                    {
                        "description": "Query details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LLMQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/LLMQueryResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/llm/query/stream": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Stream LLM responses using Server-Sent Events (SSE). Returns tokens as they are generated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "LLM"
                ],
                "summary": "Stream LLM query",
                "parameters": [
                    {
                        "description": "Query details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LLMQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Returns SSE stream of tokens"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/settings/categories": {
            "get": {
                "description": "Get all available feed categories",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Settings"
                ],
                "summary": "Get categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/CategoriesResponse"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "description": "WebSocket endpoint for real-time feed streaming. Connect and send authentication message, then subscribe to feeds. For testing, use CLI tools like wscat or Postman with WebSocket support.",
                "tags": [
                    "WebSocket"
                ],
                "summary": "WebSocket streaming endpoint",
                "responses": {
                    "101": {
                        "description": "Switching Protocols - WebSocket connection established"
                    }
                }
            }
        }
    },
    "definitions": {
        "HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "mongodb": "connected"
                    }
                },
                "timestamp": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "example": "securePassword123"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "format": "email",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "format": "password",
                    "example": "securePassword123"
                },
                "totpToken": {
                    "type": "string",
                    "description": "TOTP code if 2FA is enabled",
                    "example": "123456"
                }
            }
        },
        "AuthResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "Login successful"
                },
                "token": {
                    "type": "string",
                    "description": "JWT authentication token",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "$ref": "#/definitions/User"
                }
            }
        },
        "UserProfileResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "user": {
                    "$ref": "#/definitions/User"
                }
            }
        },
        "User": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "tokenUsage": {
                    "$ref": "#/definitions/TokenUsage"
                },
                "twoFactorEnabled": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "TokenUsage": {
            "type": "object",
            "properties": {
                "currentMonth": {
                    "type": "string",
                    "example": "2025-01"
                },
                "tokensUsed": {
                    "type": "integer",
                    "example": 1500
                },
                "limit": {
                    "type": "integer",
                    "example": 1000000
                },
                "lastResetDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "overdraftAllowed": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "CreateFeedRequest": {
            "type": "object",
            "required": [
                "name",
                "description",
                "url",
                "category",
                "isPublic",
                "connectionType"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Binance BTC/USDT"
                },
                "description": {
                    "type": "string",
                    "example": "Real-time Bitcoin price feed from Binance"
                },
                "url": {
                    "type": "string",
                    "example": "wss://stream.binance.com:9443/ws/btcusdt@trade"
                },
                "category": {
                    "type": "string",
                    "example": "cryptocurrency"
                },
                "isPublic": {
                    "type": "boolean",
                    "example": true
                },
                "connectionType": {
                    "type": "string",
                    "enum": [
                        "websocket",
                        "http"
                    ],
                    "example": "websocket"
                },
                "enableTopicRouting": {
                    "type": "boolean",
                    "description": "Enable topic-based routing for this feed",
                    "example": false
                },
                "topicField": {
                    "type": "string",
                    "description": "JSON field name to use for topic identification",
                    "example": "symbol"
                },
                "connectionMessages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "Messages to send on connection",
                    "example": [
                        "{\"method\":\"SUBSCRIBE\",\"params\":[\"btcusdt@trade\"],\"id\":1}"
                    ]
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "bitcoin",
                        "trading",
                        "real-time"
                    ]
                }
            }
        },
        "UpdateFeedRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "defaultAIPrompt": {
                    "type": "string"
                },
                "aiAnalysisEnabled": {
                    "type": "boolean"
                }
            }
        },
        "FeedResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "data": {
                    "$ref": "#/definitions/Feed"
                }
            }
        },
        "FeedsListResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "count": {
                    "type": "integer",
                    "example": 10
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Feed"
                    }
                }
            }
        },
        "Feed": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "name": {
                    "type": "string",
                    "example": "Binance BTC/USDT"
                },
                "description": {
                    "type": "string",
                    "example": "Real-time Bitcoin price feed"
                },
                "url": {
                    "type": "string",
                    "example": "wss://stream.binance.com:9443/ws/btcusdt@trade"
                },
                "category": {
                    "type": "string",
                    "example": "cryptocurrency"
                },
                "isPublic": {
                    "type": "boolean",
                    "example": true
                },
                "isActive": {
                    "type": "boolean",
                    "example": true
                },
                "connectionType": {
                    "type": "string",
                    "example": "websocket"
                },
                "enableTopicRouting": {
                    "type": "boolean",
                    "example": false
                },
                "topicField": {
                    "type": "string",
                    "example": "symbol"
                },
                "subscriberCount": {
                    "type": "integer",
                    "example": 42
                },
                "userId": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "ownerName": {
                    "type": "string",
                    "example": "John Doe"
                },
                "createdAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "updatedAt": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "SubscriptionResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "Subscribed successfully"
                },
                "subscription": {
                    "$ref": "#/definitions/Subscription"
                }
            }
        },
        "SubscriptionsListResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "count": {
                    "type": "integer",
                    "example": 5
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Subscription"
                    }
                }
            }
        },
        "Subscription": {
            "type": "object",
            "properties": {
                "_id": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "userId": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "feedId": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439012"
                },
                "subscribedAt": {
                    "type": "string",
                    "format": "date-time"
                },
                "isActive": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "LLMQueryRequest": {
            "type": "object",
            "required": [
                "feedId",
                "question"
            ],
            "properties": {
                "feedId": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "question": {
                    "type": "string",
                    "example": "What is the current Bitcoin price trend?"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "openai",
                        "anthropic",
                        "google",
                        "mistral",
                        "xai",
                        "ollama",
                        "azure"
                    ],
                    "example": "anthropic"
                },
                "systemPrompt": {
                    "type": "string",
                    "description": "Custom system prompt (optional)",
                    "example": "You are a cryptocurrency trading analyst."
                }
            }
        },
        "LLMQueryResponse": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "Based on the recent data, Bitcoin is showing an upward trend..."
                },
                "provider": {
                    "type": "string",
                    "example": "anthropic"
                },
                "feedId": {
                    "type": "string",
                    "example": "507f1f77bcf86cd799439011"
                },
                "tokensUsed": {
                    "type": "integer",
                    "example": 150
                },
                "durationMs": {
                    "type": "integer",
                    "example": 1250
                }
            }
        },
        "ProvidersResponse": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean",
                    "example": true
                },
                "providers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "openai",
                        "anthropic",
                        "google"
                    ]
                }
            }
        },
        "CategoriesResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "key": {
                                "type": "string",
                                "example": "cryptocurrency"
                            },
                            "label": {
                                "type": "string",
                                "example": "Cryptocurrency"
                            }
                        }
                    }
                }
            }
        },
        "SuccessResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Error message describing what went wrong"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type 'Bearer' followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Health check endpoints",
            "name": "Health"
        },
        {
            "description": "User authentication and authorization",
            "name": "Authentication"
        },
        {
            "description": "Feed marketplace and subscription management",
            "name": "Marketplace"
        },
        {
            "description": "Application settings and categories",
            "name": "Settings"
        },
        {
            "description": "AI/LLM integration for feed analysis",
            "name": "LLM"
        },
        {
            "description": "Real-time WebSocket streaming (test in CLI or Postman)",
            "name": "WebSocket"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7210",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TurboStream API",
	Description:      "TurboStream API for real-time data streaming and feed management with AI-powered analysis",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
